---
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - ruby-head
before_install:
  - gem update --system
  - gem update bundler

gemfile:
  - gemfiles/activerecord_52.gemfile
  - gemfiles/activerecord_60.gemfile
  - gemfiles/activerecord_edge.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/activerecord_edge.gemfile
